const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Audio.Acts.SetPaused
	];
};
self.C3_JsPropNameTable = [
	{girisarkpln: 0},
	{arkpln: 0},
	{bilgiarkpln: 0},
	{tebrklrArkPln: 0},
	{Butonlar: 0},
	{Fare: 0},
	{Dokun: 0},
	{Dizi: 0},
	{SPR_SoruNo: 0},
	{SPR_Secenekler: 0},
	{Yazı: 0},
	{salyangozvekabugu: 0},
	{Dizi2: 0},
	{Ses: 0},
	{YerelKayıtAlanı: 0},
	{SPR_Donut: 0},
	{Yazı2: 0},
	{kap: 0},
	{soruNo: 0},
	{puan: 0},
	{secimyapildi: 0},
	{i: 0},
	{j: 0}
];

self.InstanceType = {
	girisarkpln: class extends self.ISpriteInstance {},
	arkpln: class extends self.ISpriteInstance {},
	bilgiarkpln: class extends self.ISpriteInstance {},
	tebrklrArkPln: class extends self.ISpriteInstance {},
	Butonlar: class extends self.ISpriteInstance {},
	Fare: class extends self.IInstance {},
	Dokun: class extends self.IInstance {},
	Dizi: class extends self.IArrayInstance {},
	SPR_SoruNo: class extends self.ISpriteInstance {},
	SPR_Secenekler: class extends self.ISpriteInstance {},
	Yazı: class extends self.ITextInstance {},
	salyangozvekabugu: class extends self.ISpriteInstance {},
	Dizi2: class extends self.IArrayInstance {},
	Ses: class extends self.IInstance {},
	YerelKayıtAlanı: class extends self.IInstance {},
	SPR_Donut: class extends self.ISpriteInstance {},
	Yazı2: class extends self.ITextInstance {},
	kap: class extends self.ISpriteInstance {}
}